name: Test
on:
  push:
    branches-ignore:
      - main
jobs:
  poke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3 
      - name: Check For YQ
        id: checkyq
        run: |
          export OLD_VERSION=`yq .version nttchart/Chart.yaml`
          export NEW_VERSION=`echo "import os;vbits=os.environ.get('OLD_VERSION').rsplit('.');print('.'.join([*vbits[0:-1], str(int(vbits[-1])+1)]))" | python3`
          echo "Migrating chart from $OLD_VERSION to $NEW_VERSION"
          yq -i '.version = strenv(NEW_VERSION)' nttchart/Chart.yaml
          yq .version nttchart/Chart.yaml
