namespace: ntt
uiAppName: ntt-ui
uiAppReplicas: 1
uiImageVers: 0.0.18
uiImagePath: registry.gitlab.com/micahgalizia/jefftrees-ui
uiImageSecret: gitlab-ntt-ui

apiAppName: ntt-api
apiAppReplicas: 1
apiImageVers: 0.0.6
apiImagePath: ghcr.io/micahg/nttsrv

mongoName: "mongo"
mongoImagePath: mongo
mongoImageVers: 7.0.0
mongoPort: 27017
